INFO | SETTINGS FILE: gp2\settings\settings.default.json

INFO | SETTINGS FILE: settings\settings.rx.json

CRITICAL | UNANDLED_EXCEPTION
Traceback (most recent call last):
  File "C:\Users\redmo\Anaconda3\envs\Finance\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\redmo\Anaconda3\envs\Finance\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\RedXCapital\crypto\ETL_update_data_model\gp2\runner\__init__.py", line 1, in <module>
    from .__runner import run_steps
  File "D:\RedXCapital\crypto\ETL_update_data_model\gp2\runner\__runner.py", line 10, in <module>
    from gp2.job import TMP_DIR
  File "D:\RedXCapital\crypto\ETL_update_data_model\gp2\job\__init__.py", line 3, in <module>
    from .__job import (
  File "D:\RedXCapital\crypto\ETL_update_data_model\gp2\job\__job.py", line 158, in <module>
    jobinfo                 = get_jobinfo()
  File "D:\RedXCapital\crypto\ETL_update_data_model\gp2\job\__jobinfo.py", line 81, in get_jobinfo
    ji = __get_jobinfo_from_context()
  File "D:\RedXCapital\crypto\ETL_update_data_model\gp2\job\__jobinfo.py", line 43, in __get_jobinfo_from_context
    ji.git_hash        = subprocess.run(['git', 'rev-parse', 'HEAD'           ], capture_output=True, check=True).stdout.decode('ascii').strip()
  File "C:\Users\redmo\Anaconda3\envs\Finance\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
CRITICAL | UNEXPECTED EXIT

